### ISSUE TITLE
I had a previous version and wanted to update but it failed.

### ISSUE THREAD

**Issue by samsungrocks10** [XeliteXirish/EliteSelfBot#3]
I went to update the version of the selfbot that I have but it errors out, so I went and downloaded the latest version from github, extracted it and installed, but when I start it it crashes.
```
E:\Downloads\EliteSelfBot (1)>npm start

> eliteselfbot@1.0.0 start E:\Downloads\EliteSelfBot (1)
> nodemon src/bot

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/bot bot.js`
E:\Downloads\EliteSelfBot (1)\src\bot.js:120
    let errorMsg = err.stack.replace(new RegExp(`${__dirname}\/`, 'g'), './');
                      ^

TypeError: Cannot read property 'stack' of undefined
    at process.on (E:\Downloads\EliteSelfBot (1)\src\bot.js:120:23)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (E:\Downloads\EliteSelfBot (1)\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
    at process._fatalException (bootstrap_node.js:296:26)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by ubscal** [comment]
same issue

**Comment by XeliteXirish** [comment]
Alright il get it fixed tonight, thanks

**Comment by KrisNorrell** [comment]
it appears that i am having the same issue as stated above
