### ISSUE TITLE
starting issue

### ISSUE THREAD

**Issue by jonathanjosephz** [XeliteXirish/EliteSelfBot#5]
[nodemon] 1.17.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/bot.js`
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'sqlite'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Jonathan\Desktop\dself\src\bot.js:27:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
[nodemon] app crashed - waiting for file changes before starting...

> Please help with this. Thank you

**Comment by TheRedstoney2000** [comment]
Hmm, try going into the main directory (Where the .git files are) and doing npm install
oof this repo is dusty too
